// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceAPI.DataAccess;

namespace ServiceAPI.Migrations
{
    [DbContext(typeof(StatsDbContext))]
    [Migration("20200319103905_RemovedStaticHospitalData")]
    partial class RemovedStaticHospitalData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceAPI.Models.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GlobalDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GlobalNewCases")
                        .HasColumnType("int");

                    b.Property<int>("GlobalNewDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GlobalRecovered")
                        .HasColumnType("int");

                    b.Property<int>("GlobalTotalCases")
                        .HasColumnType("int");

                    b.Property<int>("LocalDeaths")
                        .HasColumnType("int");

                    b.Property<int>("LocalNewCases")
                        .HasColumnType("int");

                    b.Property<int>("LocalNewDeaths")
                        .HasColumnType("int");

                    b.Property<int>("LocalRecovered")
                        .HasColumnType("int");

                    b.Property<int>("LocalTotalCases")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("ServiceAPI.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "National Institute of Infectious Diseases"
                        },
                        new
                        {
                            Id = 2,
                            Name = "National Hospital Sri Lanka"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TH - Ragama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TH - Karapitiya"
                        },
                        new
                        {
                            Id = 5,
                            Name = "TH - Anuradhapura"
                        },
                        new
                        {
                            Id = 6,
                            Name = "TH - Kurunegala"
                        },
                        new
                        {
                            Id = 7,
                            Name = "TH- Jaffna"
                        },
                        new
                        {
                            Id = 8,
                            Name = "National Hospital Kandy"
                        },
                        new
                        {
                            Id = 9,
                            Name = "TH – Batticaloa"
                        },
                        new
                        {
                            Id = 10,
                            Name = "DGH- Gampaha"
                        },
                        new
                        {
                            Id = 11,
                            Name = "DGH – Negombo"
                        },
                        new
                        {
                            Id = 12,
                            Name = "TH – Rathnapura"
                        },
                        new
                        {
                            Id = 13,
                            Name = "PGH – Badulla"
                        },
                        new
                        {
                            Id = 14,
                            Name = "LRH"
                        },
                        new
                        {
                            Id = 15,
                            Name = "DMH"
                        },
                        new
                        {
                            Id = 16,
                            Name = "DGH – Polonnaruwa"
                        },
                        new
                        {
                            Id = 17,
                            Name = "TH - Kalubowila"
                        });
                });

            modelBuilder.Entity("ServiceAPI.Models.HospitalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CumulativeForeign")
                        .HasColumnType("int");

                    b.Property<int>("CumulativeLocal")
                        .HasColumnType("int");

                    b.Property<int>("CumulativeTotal")
                        .HasColumnType("int");

                    b.Property<int?>("DashboardId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentForeign")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentLocal")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.ToTable("HospitalStats");
                });

            modelBuilder.Entity("ServiceAPI.Models.HospitalData", b =>
                {
                    b.HasOne("ServiceAPI.Models.Dashboard", null)
                        .WithMany("HospitalData")
                        .HasForeignKey("DashboardId");
                });
#pragma warning restore 612, 618
        }
    }
}
